version: "3.9"

services:
  db:
    image: mysql
    # Prevent mysql authentication error
    command: --default-authentication-plugin=mysql_native_password
    volumes:
      - /home/thinklim/db-data:/var/lib/mysql
    environment:
      - MYSQL_ROOT_PASSWORD=tutorialpw
      - MYSQL_DATABASE=tutorialdb
      - MYSQL_USER=tutorial
      - MYSQL_PASSWORD=tutorialpw
  web:
    build: .
    command: python manage.py runserver 0.0.0.0:8000
    volumes:
      - .:/tutorial
    ports:
      - 9000:8000
    depends_on:
      - db
